// Administration: staff & roles, audit log, my activity, players, settings, my account.
import * as S from './store.js';
import * as Auth from './auth.js';
import { icon } from './icons.js';
import { ui, esc, val, toast, modal, closeModal, head, pill, kpi, table, defineView, defineActions, render } from './ui.js';
import { money, fmtDT, fmtKey, dayKey, durFmt, now } from './store.js';
import { PERM_GROUPS, ROLE_LABEL, ADMIN_ONLY, DEFAULT_ROLES, pwProblem, pinProblem, setSecrets } from './auth.js';
import { xlsxBlob, download } from './export.js';
import { visitsAll, groupPlayers } from './mgmt.js';
import { TYPES } from './approvals.js';

const can = Auth.can, me = () => S.ctx.actor;
const DAYN = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const activeAdmins = () => S.get().users.filter(u => u.role === 'admin' && u.active);

// ---------- staff & roles ----------
defineView({ route: 'staff', label: 'Staff & Roles', icon: 'members', group: 'Administration', perm: ['staff.manage', 'roles.manage'],
  render() {
    const s = S.get(), tab = ui.staffTab;
    const rows = s.users.map(u => ({ name: u.name, user: u.username, role: ROLE_LABEL[u.role] || u.role, pos: u.position, emp: u.employeeNo, status: u.active ? pill('Active', 'green') : pill('Deactivated', 'red'), act0: u.active ? 1 : 0, last: u.lastLogin, act: `<div class="row" style="gap:6px;flex-wrap:wrap"><button class="btn sm secondary" data-a="staffEdit" data-id="${u.id}">Edit</button><button class="btn sm secondary" data-a="staffReset" data-id="${u.id}" data-k="pw">Reset password</button><button class="btn sm secondary" data-a="staffReset" data-id="${u.id}" data-k="pin">Reset PIN</button><button class="btn sm ${u.active ? 'orange' : ''}" data-a="staffActive" data-id="${u.id}">${u.active ? 'Deactivate' : 'Reactivate'}</button></div>` }));
    let body = '';
    if (tab === 'staff') body = `<div class="card white"><div class="row" style="justify-content:space-between"><h2>Staff accounts</h2>${can('staff.manage') ? `<button class="btn" data-a="staffNew">${icon('plus')} Create account</button>` : ''}</div>${table('staff', [{ key: 'name', label: 'Name' }, { key: 'user', label: 'Username' }, { key: 'role', label: 'Role' }, { key: 'pos', label: 'Position' }, { key: 'emp', label: 'Emp. no.' }, { key: 'status', label: 'Status', type: 'html', sortKey: 'act0' }, { key: 'last', label: 'Last sign-in', type: 'dt' }, { key: 'act', label: '', type: 'html' }], rows, { sort: { key: 'name', dir: 'asc' } })}<p class="muted" style="font-size:12px;margin-top:8px">Every staff member has an individual account and PIN. Passwords and PINs are stored only as salted hashes — nobody, including Management, can read them.</p></div>`;
    else body = `<div class="card white"><div class="row" style="justify-content:space-between"><h2>Role permissions</h2>${can('roles.manage') ? `<button class="btn secondary" data-a="rolesReset">Reset to defaults</button>` : ''}</div><p class="muted">Tick what each role may do. Items marked <span class="pill orange">${icon('alert', 12)} Management only</span> can never be given to other roles (separation of duties).</p><div class="tablewrap"><table class="permtable"><thead><tr><th>Permission</th>${['admin', 'cashier', 'attendant', 'server'].map(r => `<th class="center">${ROLE_LABEL[r]}</th>`).join('')}</tr></thead><tbody>${PERM_GROUPS.map(([g, list]) => `<tr class="grp"><td colspan="5">${g}</td></tr>${list.map(([k, l]) => `<tr><td>${esc(l)}${ADMIN_ONLY.includes(k) ? ` <span class="pill orange">Management only</span>` : ''}</td>${['admin', 'cashier', 'attendant', 'server'].map(r => { const on = s.roles[r].perms.includes(k), lock = r === 'admin' || ADMIN_ONLY.includes(k) || !can('roles.manage'); return `<td class="center"><input type="checkbox" ${on ? 'checked' : ''} ${lock ? 'disabled' : ''} data-change="permToggle" data-role="${r}" data-perm="${k}" aria-label="${esc(l)} for ${ROLE_LABEL[r]}"></td>`; }).join('')}</tr>`).join('')}`).join('')}</tbody></table></div></div>`;
    return head('Staff & Roles', 'Individual accounts, roles and permissions.') + `<div class="tabs-seg" style="margin-bottom:16px">${[['staff', 'Staff accounts'], ['roles', 'Roles & permissions']].map(([k, l]) => `<button class="${tab === k ? 'on' : ''}" data-a="staffTab" data-k="${k}">${l}</button>`).join('')}</div>${body}`;
  } });

const schedForm = (sc = { start: '08:00', end: '17:00', hours: 8, restDays: [] }) => `<div class="grid g2" style="gap:12px"><div class="field"><label for="sf_s">Shift starts</label><input type="time" id="sf_s" value="${sc.start}"></div><div class="field"><label for="sf_e">Shift ends</label><input type="time" id="sf_e" value="${sc.end}"></div><div class="field"><label for="sf_h">Paid hours per day</label><input type="number" id="sf_h" step="0.5" min="1" max="16" value="${sc.hours}"></div></div><div class="field"><label>Weekly rest day(s)</label><div class="row" style="gap:10px">${DAYN.map((d, i) => `<label style="display:inline-flex;gap:4px;align-items:center;margin:0;font-weight:500"><input type="checkbox" style="width:auto;min-height:0" class="sf_r" value="${i}" ${sc.restDays.includes(i) ? 'checked' : ''}>${d}</label>`).join('')}</div></div>`;
const readSched = () => ({ start: val('sf_s') || '08:00', end: val('sf_e') || '17:00', hours: +val('sf_h') || 8, restDays: [...document.querySelectorAll('.sf_r:checked')].map(x => +x.value) });
const roleOpts = sel => ['cashier', 'attendant', 'server', 'admin'].map(r => `<option value="${r}" ${sel === r ? 'selected' : ''}>${ROLE_LABEL[r]}</option>`).join('');

defineActions({
  staffTab: [['staff.manage', 'roles.manage'].join('|'), d => { ui.staffTab = d.k; render(); }],
  staffNew: ['staff.manage', () => modal(`<h2>Create staff account</h2><div class="grid g2" style="gap:12px"><div class="field"><label for="n_name">Full name</label><input id="n_name"></div><div class="field"><label for="n_user">Username</label><input id="n_user" autocomplete="off" placeholder="e.g. cashier3"></div><div class="field"><label for="n_role">Role</label><select id="n_role">${roleOpts('cashier')}</select></div><div class="field"><label for="n_pos">Position</label><input id="n_pos" placeholder="e.g. Counter / Cashier"></div><div class="field"><label for="n_emp">Employee no.</label><input id="n_emp"></div><div class="field"><label for="n_pw">Temporary password</label><input id="n_pw" type="password" autocomplete="new-password"></div><div class="field"><label for="n_pin">PIN (4–6 digits)</label><input id="n_pin" type="password" inputmode="numeric" autocomplete="off"></div></div><h3 style="margin:6px 0 10px">Work schedule</h3>${schedForm()}<div class="foot"><button class="btn secondary" data-a="close">Cancel</button><button class="btn" data-a="staffCreate">Create account</button></div>`, true)],
  staffCreate: ['staff.manage', () => {
    const name = val('n_name').trim(), un = val('n_user').trim().toLowerCase(), role = val('n_role'), pw = val('n_pw'), pin = val('n_pin');
    if (!name || !un) return toast('Name and username are required', 'err'); if (!/^[a-z0-9._-]{3,24}$/.test(un)) return toast('Username: 3–24 letters, numbers, . _ -', 'err');
    if (S.get().users.some(u => u.username === un)) return toast('That username is taken', 'err');
    const e = pwProblem(pw) || pinProblem(pin); if (e) return toast(e, 'err');
    S.commit(s => { const u = { id: 'u' + (++s.seq), username: un, name, role, position: val('n_pos').trim() || ROLE_LABEL[role], employeeNo: val('n_emp').trim(), active: true, schedule: readSched(), createdAt: S.now(), createdBy: me().id, failed: 0, lockUntil: 0, lastLogin: null }; setSecrets(u, { password: pw, pin }); s.users.push(u); S.log(s, 'staff_created', `Account created: ${name} (${un}) as ${ROLE_LABEL[role]}`); });
    closeModal(); toast('Account created');
  }],
  staffEdit: ['staff.manage', d => { const u = S.userById(d.id), self = u.id === me().id; modal(`<h2>Edit ${esc(u.name)}</h2><div class="grid g2" style="gap:12px"><div class="field"><label for="e_name">Full name</label><input id="e_name" value="${esc(u.name)}"></div><div class="field"><label for="e_role">Role</label><select id="e_role" ${self ? 'disabled' : ''}>${roleOpts(u.role)}</select></div><div class="field"><label for="e_pos">Position</label><input id="e_pos" value="${esc(u.position)}"></div><div class="field"><label for="e_emp">Employee no.</label><input id="e_emp" value="${esc(u.employeeNo || '')}"></div></div>${schedForm(u.schedule)}<div class="field"><label for="e_why">Reason for change (required)</label><input id="e_why"></div><div class="foot"><button class="btn secondary" data-a="close">Cancel</button><button class="btn" data-a="staffSave" data-id="${u.id}">Save</button></div>`, true); }],
  staffSave: ['staff.manage', d => {
    const why = val('e_why').trim(); if (!why) return toast('A reason is required', 'err'); const role = val('e_role') || S.userById(d.id).role, nm = val('e_name').trim(); if (!nm) return toast('Name required', 'err');
    if (d.id === me().id && role !== 'admin') return toast('You cannot change your own role', 'err');
    if (S.userById(d.id).role === 'admin' && role !== 'admin' && activeAdmins().length <= 1) return toast('At least one active administrator is required', 'err');
    S.commit(s => { const u = S.userById(d.id), before = `${u.name}/${u.role}/${u.position}`; Object.assign(u, { name: nm, role, position: val('e_pos').trim(), employeeNo: val('e_emp').trim(), schedule: readSched() }); S.log(s, 'staff_edited', `Account edited: ${before} → ${u.name}/${u.role}/${u.position} — ${why}`); }); closeModal(); toast('Saved');
  }],
  staffReset: ['staff.manage', d => { const u = S.userById(d.id), pw = d.k === 'pw'; modal(`<h2>Reset ${pw ? 'password' : 'PIN'} — ${esc(u.name)}</h2><div class="field"><label for="r_new">New ${pw ? 'temporary password' : 'PIN (4–6 digits)'}</label><input id="r_new" type="password" autocomplete="new-password" ${pw ? '' : 'inputmode="numeric"'}></div><div class="field"><label for="r_why">Reason (required)</label><input id="r_why" placeholder="e.g. Forgot password"></div><div class="foot"><button class="btn secondary" data-a="close">Cancel</button><button class="btn" data-a="staffResetDo" data-id="${u.id}" data-k="${d.k}">Reset</button></div>`); }],
  staffResetDo: ['staff.manage', d => { const pw = d.k === 'pw', v = val('r_new'), why = val('r_why').trim(); if (!why) return toast('A reason is required', 'err'); const e = pw ? pwProblem(v) : pinProblem(v); if (e) return toast(e, 'err'); S.commit(s => { const u = S.userById(d.id); setSecrets(u, pw ? { password: v } : { pin: v }); u.failed = 0; u.lockUntil = 0; S.log(s, pw ? 'password_reset' : 'pin_reset', `${pw ? 'Password' : 'PIN'} reset for ${u.name} — ${why}`); }); closeModal(); toast(`${pw ? 'Password' : 'PIN'} reset`); }],
  staffActive: ['staff.manage', d => { const u = S.userById(d.id), on = !u.active; if (!on && u.id === me().id) return toast('You cannot deactivate your own account', 'err'); if (!on && u.role === 'admin' && activeAdmins().length <= 1) return toast('At least one active administrator is required', 'err'); modal(`<h2>${on ? 'Reactivate' : 'Deactivate'} ${esc(u.name)}?</h2><p class="muted">${on ? 'They will be able to sign in again.' : 'They are signed out immediately and cannot sign in. Their history is kept.'}</p><div class="field"><label for="a_why">Reason (required)</label><input id="a_why"></div><div class="foot"><button class="btn secondary" data-a="close">Cancel</button><button class="btn ${on ? '' : 'orange'}" data-a="staffActiveDo" data-id="${u.id}">${on ? 'Reactivate' : 'Deactivate'}</button></div>`); }],
  staffActiveDo: ['staff.manage', d => { const why = val('a_why').trim(); if (!why) return toast('A reason is required', 'err'); const u0 = S.userById(d.id); if (u0.active && (u0.id === me().id || (u0.role === 'admin' && activeAdmins().length <= 1))) return toast('Not allowed', 'err'); S.commit(s => { const u = S.userById(d.id); u.active = !u.active; if (!u.active) s.logins.filter(l => l.userId === u.id && !l.logoutAt).forEach(l => { l.logoutAt = S.now(); l.logoutISO = S.manilaISO(l.logoutAt); l.logoutReason = 'deactivated'; }); S.log(s, u.active ? 'staff_reactivated' : 'staff_deactivated', `${u.name} ${u.active ? 'reactivated' : 'deactivated'} — ${why}`); }); closeModal(); toast('Updated'); }],
  permToggle: ['roles.manage', (d, e, el) => { if (d.role === 'admin' || ADMIN_ONLY.includes(d.perm)) return render(); S.commit(s => { const p = s.roles[d.role].perms, on = el.checked; if (on && !p.includes(d.perm)) p.push(d.perm); if (!on) s.roles[d.role].perms = p.filter(x => x !== d.perm); S.log(s, 'permission_change', `${ROLE_LABEL[d.role]}: "${d.perm}" ${on ? 'granted' : 'removed'}`); }); }],
  rolesReset: ['roles.manage', () => { S.commit(s => { const d = DEFAULT_ROLES(); ['cashier', 'attendant', 'server'].forEach(r => { s.roles[r].perms = d[r].perms; }); S.log(s, 'permission_change', 'Role permissions reset to defaults'); }); toast('Roles reset to defaults'); }],
});

// ---------- audit log ----------
defineView({ route: 'audit', label: 'Audit Log', icon: 'shield', group: 'Administration', perm: 'audit.viewAll',
  render() {
    const s = S.get(), f = ui.auditF, v = S.verifyAudit(), tab = ui.auditTab || 'log';
    const types = [...new Set(s.audit.map(a => a.type))].sort(), users = [...new Map(s.audit.map(a => [a.userId, a.user])).entries()];
    const list = s.audit.filter(a => (f.user === 'all' || a.userId === f.user) && (f.type === 'all' || a.type === f.type)).slice().reverse();
    const rows = list.slice(0, 500).map(a => ({ seq: a.seq, at: a.ts, user: a.user, role: ROLE_LABEL[a.role] || a.role, type: a.type.replace(/_/g, ' '), msg: a.msg, dev: a.device || '' }));
    const lrows = s.logins.slice().reverse().slice(0, 300).map(l => ({ user: l.userName, role: ROLE_LABEL[l.role] || l.role, inAt: l.loginAt, outAt: l.logoutAt, dur: l.logoutAt ? (l.logoutAt - l.loginAt) / 60e3 : null, why: l.logoutAt ? ({ logout: 'Signed out', timeout: 'Idle timeout', deactivated: 'Deactivated' })[l.logoutReason] || l.logoutReason : 'Still signed in', dev: l.device }));
    return head('Audit Log', 'Append-only record of every user action. Entries cannot be edited or deleted.', can('reports.export') ? `<button class="btn secondary" data-a="auditXlsx">${icon('inventory')} Export Excel</button>` : '') + `
      <div class="notice ${v.ok ? 'green' : 'red'}">${icon(v.ok ? 'check' : 'alert')} ${v.ok ? `Integrity check passed — ${v.total} entries form an unbroken hash chain.` : `<b>Tampering detected</b> at entry #${v.brokenAt} of ${v.total}. The log was altered outside the application.`}</div>
      <div class="tabs-seg" style="margin-bottom:14px">${[['log', 'Actions'], ['logins', 'Sign-ins & devices']].map(([k, l]) => `<button class="${tab === k ? 'on' : ''}" data-a="auditTab" data-k="${k}">${l}</button>`).join('')}</div>` + (tab === 'log' ? `
      <div class="filterbar"><select data-change="auditFilter" data-k="user" style="width:auto" aria-label="User"><option value="all">All users</option>${users.map(([id, n]) => `<option value="${id}" ${f.user === id ? 'selected' : ''}>${esc(n)}</option>`).join('')}</select><select data-change="auditFilter" data-k="type" style="width:auto" aria-label="Event"><option value="all">All events</option>${types.map(t => `<option value="${t}" ${f.type === t ? 'selected' : ''}>${t.replace(/_/g, ' ')}</option>`).join('')}</select><span class="muted">${list.length} entries</span></div>
      ${table('audit', [{ key: 'seq', label: '#', type: 'int' }, { key: 'at', label: 'Date & time (PHT)', type: 'dt' }, { key: 'user', label: 'User' }, { key: 'role', label: 'Role' }, { key: 'type', label: 'Event' }, { key: 'msg', label: 'Details' }, { key: 'dev', label: 'Device / session' }], rows, { sort: { key: 'seq', dir: 'desc' }, limit: 500 })}` : table('logins', [{ key: 'user', label: 'User' }, { key: 'role', label: 'Role' }, { key: 'inAt', label: 'Sign-in', type: 'dt' }, { key: 'outAt', label: 'Sign-out', type: 'dt' }, { key: 'dur', label: 'Duration', type: 'dur' }, { key: 'why', label: 'Ended' }, { key: 'dev', label: 'Device' }], lrows, { sort: { key: 'inAt', dir: 'desc' } }));
  } });
defineActions({
  auditTab: ['audit.viewAll', d => { ui.auditTab = d.k; render(); }],
  auditFilter: ['audit.viewAll', (d, e, el) => { ui.auditF[d.k] = el.value; render(); }],
  auditXlsx: ['reports.export', () => { const s = S.get(), f = ui.auditF, list = s.audit.filter(a => (f.user === 'all' || a.userId === f.user) && (f.type === 'all' || a.type === f.type)).slice().reverse(); download(xlsxBlob('Audit log', ['Cattle Creek Country Club', `Exported ${fmtDT(now())} PHT by ${me().name}`], [{ key: 'seq', label: '#', type: 'int' }, { key: 'at', label: 'Date & time (PHT)', type: 'dt' }, { key: 'user', label: 'User' }, { key: 'role', label: 'Role' }, { key: 'type', label: 'Event' }, { key: 'msg', label: 'Details' }, { key: 'device', label: 'Device' }, { key: 'hash', label: 'Hash' }], list.map(a => ({ ...a, at: a.ts, role: ROLE_LABEL[a.role] || a.role }))), `Cattle-Creek_audit-log_${dayKey(now())}.xlsx`); S.commit(st => S.log(st, 'report_export', 'Exported audit log to Excel')); }],
});

// ---------- my activity ----------
defineView({ route: 'activity', label: 'My Activity', icon: 'clock', group: 'People', perm: 'activity.own',
  render() {
    const s = S.get(), u = Auth.user(), mine = s.audit.filter(a => a.userId === u.id).slice().reverse().slice(0, 150).map(a => ({ at: a.ts, type: a.type.replace(/_/g, ' '), msg: a.msg }));
    const reqs = s.approvals.filter(a => a.requestedBy === u.id).slice().reverse().slice(0, 50).map(a => ({ at: a.requestedAt, type: TYPES[a.type], ref: a.refLabel, amount: a.amount, status: a.status === 'pending' ? 'Waiting for approval' : a.status === 'approved' ? 'Approved' : 'Rejected', by: a.decidedByName || '—', note: a.decisionNote }));
    return head('My Activity', `Everything recorded under your account (${esc(u.name)}).`) + `<div class="card white"><h2>My activity history</h2>${table('myact', [{ key: 'at', label: 'Date & time', type: 'dt' }, { key: 'type', label: 'Event' }, { key: 'msg', label: 'Details' }], mine, { sort: { key: 'at', dir: 'desc' }, limit: 150 })}</div>${reqs.length ? `<div class="card white" style="margin-top:18px"><h2>My approval requests</h2>${table('myreq', [{ key: 'at', label: 'Requested', type: 'dt' }, { key: 'type', label: 'Request' }, { key: 'ref', label: 'Reference' }, { key: 'amount', label: 'Amount', type: 'money' }, { key: 'status', label: 'Status' }, { key: 'by', label: 'Decided by' }, { key: 'note', label: 'Note' }], reqs, { sort: { key: 'at', dir: 'desc' } })}</div>` : ''}`;
  } });

// ---------- players ----------
defineView({ route: 'players', label: 'Players', icon: 'member', group: 'People', perm: 'players.view',
  render() {
    const s = S.get(), vs = visitsAll(), g = groupPlayers(vs).sort((a, b) => b.total - a.total), byId = new Map(g.map(x => [x.id, x]));
    const rows = s.players.map(p => { const x = byId.get(p.id); return { name: p.name, type: p.memberId ? 'Member' : 'Guest', visits: x?.visits || 0, last: x?.last || null, total: x?.total || 0, avg: x?.avg || 0, first: x?.first === Infinity ? null : x?.first || null, act: `<button class="btn sm secondary" data-a="playerHist" data-id="${p.id}">History</button>`, _s: p.name.toLowerCase() }; });
    return head('Players', 'Player database and visitor history (completed paid visits).') + `<div class="row" style="margin-bottom:12px;justify-content:space-between"><span class="muted">${s.players.length} players</span><div class="search">${icon('search', 18)}<input data-live="rows" placeholder="Search player…" aria-label="Search player"></div></div>${table('players', [{ key: 'name', label: 'Player' }, { key: 'type', label: 'Type' }, { key: 'visits', label: 'Visits', type: 'int' }, { key: 'first', label: 'First visit', type: 'dt' }, { key: 'last', label: 'Last visit', type: 'dt' }, { key: 'total', label: 'Total spent', type: 'money' }, { key: 'avg', label: 'Average spend', type: 'money' }, { key: 'act', label: '', type: 'html' }], rows, { sort: { key: 'total', dir: 'desc' } })}`;
  } });
defineActions({
  playerHist: ['players.view', d => { const s = S.get(), p = s.players.find(x => x.id === d.id), vs = visitsAll().filter(v => v.playerId === p.id).sort((a, b) => b.at - a.at); modal(`<h2>${esc(p.name)}</h2><p class="muted">${vs.length} completed visits · ${money(vs.reduce((a, v) => a + v.total, 0))} total</p><div class="tablewrap"><table><thead><tr><th>Date</th><th>Bay</th><th>Items</th><th class="right">Bill</th></tr></thead><tbody>${vs.slice(0, 60).map(v => `<tr><td>${fmtDT(v.at)}</td><td>${v.bay ? 'Bay ' + v.bay : '—'}</td><td>${v.tab.items.map(i => `${i.qty}× ${esc(i.name)}`).join(', ')}</td><td class="right">${money(v.total)}</td></tr>`).join('') || '<tr><td colspan="4" class="muted">No completed visits yet.</td></tr>'}</tbody></table></div><div class="foot"><button class="btn secondary" data-a="close">Close</button></div>`, true); }],
});

// ---------- settings ----------
defineView({ route: 'settings', label: 'Settings', icon: 'settings', group: 'Administration', perm: 'settings.manage',
  render() {
    const s = S.get(), st = s.settings;
    return head('Settings', 'Business configuration. Every change is recorded in the audit log.') + `<div class="grid g2"><div class="card white"><h2>${icon('settings')} Operations</h2>
      <div class="field"><label for="s_tax">Sales tax rate (%)</label><input id="s_tax" type="number" step="0.01" value="${(st.tax * 100).toFixed(2)}"></div>
      <div class="field"><label for="s_over">Tab marked overdue after (hours)</label><input id="s_over" type="number" value="${st.overdueHours}"></div>
      <div class="field"><label for="s_float">Opening drawer float (₱)</label><input id="s_float" type="number" step="0.01" value="${st.floatAmt}"></div>
      <div class="field"><label for="s_idle">Auto sign-out after inactivity (minutes)</label><input id="s_idle" type="number" min="1" max="120" value="${st.idleMinutes}"></div>
      <div class="field"><label for="s_grace">Late grace period (minutes)</label><input id="s_grace" type="number" min="0" value="${st.att.graceMin}"></div>
      <div class="field"><label for="s_abs">Mark absent if no clock-in after (minutes from shift start)</label><input id="s_abs" type="number" min="30" value="${st.att.absentAfterMin}"></div>
      <div class="field"><label for="s_cur">Currency</label><select id="s_cur" disabled><option>PHP – Philippine Peso (₱)</option></select></div>
      <div class="field"><label for="s_tz">Time zone</label><input id="s_tz" value="Asia/Manila (UTC+8)" disabled></div>
      <div class="field"><label for="s_bays">Driving range bays</label><input id="s_bays" value="15 bays — Bay 1 to Bay 15" disabled></div>
      <button class="btn" data-a="saveSettings">Save settings</button></div>
    <div class="card white"><h2>${icon('calendar')} Holidays</h2><p class="muted">Staff are not marked absent on holidays.</p>${s.holidays.slice().sort((a, b) => a.date.localeCompare(b.date)).map(h => `<div class="line"><div class="nm">${esc(h.name)}<div class="muted" style="font-size:12px;font-weight:500">${fmtKey(h.date)}</div></div><button class="btn sm secondary" data-a="holidayDel" data-d="${h.date}">Remove</button></div>`).join('')}<div class="row" style="margin-top:12px"><input type="date" id="h_d" style="width:auto"><input id="h_n" placeholder="Holiday name" style="flex:1"><button class="btn" data-a="holidayAdd">Add</button></div>
      <h2 style="margin-top:26px">Demo data</h2><p class="muted">Clears operational demo data (tabs, sales, stock, attendance) and re-creates the sample set. Staff accounts, roles, settings and the <b>audit log are kept</b>.</p><div class="row"><input id="rs_c" placeholder="Type RESET to confirm" style="max-width:220px"><button class="btn red" data-a="resetDemo">Reset operational data</button></div></div></div>`;
  } });
defineActions({
  saveSettings: ['settings.manage', () => {
    const n = { tax: (parseFloat(val('s_tax')) || 0) / 100, overdueHours: parseFloat(val('s_over')) || 24, floatAmt: parseFloat(val('s_float')) || 0, idleMinutes: Math.min(120, Math.max(1, parseInt(val('s_idle')) || 10)), graceMin: Math.max(0, parseInt(val('s_grace')) || 0), absentAfterMin: Math.max(30, parseInt(val('s_abs')) || 120) };
    S.commit(s => { const o = s.settings, ch = []; [['tax', o.tax, n.tax], ['overdueHours', o.overdueHours, n.overdueHours], ['floatAmt', o.floatAmt, n.floatAmt], ['idleMinutes', o.idleMinutes, n.idleMinutes], ['graceMin', o.att.graceMin, n.graceMin], ['absentAfterMin', o.att.absentAfterMin, n.absentAfterMin]].forEach(([k, a, b]) => { if (a !== b) ch.push(`${k}: ${a} → ${b}`); }); Object.assign(o, { tax: n.tax, overdueHours: n.overdueHours, floatAmt: n.floatAmt, idleMinutes: n.idleMinutes, currency: 'PHP' }); o.att.graceMin = n.graceMin; o.att.absentAfterMin = n.absentAfterMin; S.log(s, 'settings_change', ch.length ? 'Settings changed — ' + ch.join('; ') : 'Settings saved (no changes)'); });
    toast('Settings saved');
  }],
  holidayAdd: ['settings.manage', () => { const d = val('h_d'), n = val('h_n').trim(); if (!d || !n) return toast('Date and name required', 'err'); if (S.get().holidays.some(h => h.date === d)) return toast('That date is already a holiday', 'err'); S.commit(s => { s.holidays.push({ date: d, name: n }); S.log(s, 'settings_change', `Holiday added: ${n} (${d})`); }); }],
  holidayDel: ['settings.manage', d => S.commit(s => { const h = s.holidays.find(x => x.date === d.d); s.holidays = s.holidays.filter(x => x.date !== d.d); S.log(s, 'settings_change', `Holiday removed: ${h?.name} (${d.d})`); })],
  resetDemo: ['settings.manage', () => { if (val('rs_c').trim() !== 'RESET') return toast('Type RESET to confirm', 'err'); ui.cart = []; S.resetOperational(DEFAULT_ROLES()); S.commit(s => S.log(s, 'demo_reset', 'Operational demo data was reset (accounts, settings and audit log kept)')); toast('Operational data reset'); }],
});

// ---------- my account (any signed-in user) ----------
defineActions({
  myAccount: [null, () => modal(`<h2>${icon('member')} My account</h2><p class="muted">${esc(Auth.user().name)} · ${esc(Auth.roleOf(Auth.user()).label)}</p><div class="field"><label for="m_cur">Current password</label><input id="m_cur" type="password" autocomplete="current-password"></div><div class="field"><label for="m_pw">New password (optional)</label><input id="m_pw" type="password" autocomplete="new-password"></div><div class="field"><label for="m_pin">New PIN (optional, 4–6 digits)</label><input id="m_pin" type="password" inputmode="numeric" autocomplete="off"></div><div class="foot"><button class="btn secondary" data-a="close">Cancel</button><button class="btn" data-a="myAccountSave">Save</button></div>`)],
  myAccountSave: [null, () => { const u = Auth.user(), cur = val('m_cur'), pw = val('m_pw'), pin = val('m_pin'); if (!Auth.checkSecret(u, cur)) return toast('Current password is incorrect', 'err'); if (!pw && !pin) return toast('Enter a new password or PIN', 'err'); const e = (pw && pwProblem(pw)) || (pin && pinProblem(pin)); if (e) return toast(e, 'err'); S.commit(s => { setSecrets(S.userById(u.id), { password: pw, pin }); S.log(s, 'credentials_changed', `${u.name} changed their own ${[pw && 'password', pin && 'PIN'].filter(Boolean).join(' and ')}`); }); closeModal(); toast('Updated'); }],
});
