// Management Dashboard + Reports (Admin / Management only).
import * as S from './store.js';
import * as Auth from './auth.js';
import { CLUB } from './brand.js';
import { icon } from './icons.js';
import { ui, esc, val, toast, head, kpi, pill, table, fmtCell, plainCell, defineView, defineActions, render, docModal, reportDoc } from './ui.js';
import { money, price, num, hrs, durFmt, fmtDT, fmtKey, dayKey, dowOf, hourOf, manilaTs, addDays, now, stockLevel, tabTotal, isOverdue } from './store.js';
import { columns, hbars, stack, SERIES } from './charts.js';
import { attendanceToday, liveTable, ATT_REPORTS } from './attendance.js';
import { xlsxBlob, download } from './export.js';
import { ROLE_LABEL } from './auth.js';

const DAY = 86400e3, OPEN_H = 6, CLOSE_H = 21;
const weekStart = k => addDays(k, -((dowOf(manilaTs(k, '12:00')) + 6) % 7));
export function rangeFor(p) {
  const today = dayKey(now()); let f = today, t = today;
  if (p.preset === 'yesterday') f = t = addDays(today, -1);
  else if (p.preset === 'week') f = weekStart(today);
  else if (p.preset === 'month') f = today.slice(0, 8) + '01';
  else if (p.preset === 'last30') f = addDays(today, -29);
  else if (p.preset === 'custom') { f = p.from || today; t = p.to || today; if (f > t) [f, t] = [t, f]; }
  const fromTs = manilaTs(f), toTs = manilaTs(addDays(t, 1));
  return { fromKey: f, toKey: t, fromTs, toTs, days: Math.round((toTs - fromTs) / DAY), label: f === t ? fmtKey(f) : `${fmtKey(f)} – ${fmtKey(t)}` };
}
const PRESETS = [['today', 'Today'], ['yesterday', 'Yesterday'], ['week', 'This Week'], ['month', 'This Month'], ['custom', 'Custom Range']];
const inR = (r, t) => t >= r.fromTs && t < r.toTs;
const shortKey = k => new Date(manilaTs(k, '12:00')).toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'Asia/Manila' });
const hourLbl = h => `${h % 12 || 12}${h < 12 ? 'a' : 'p'}`;
const catOf = l => (l.cat === 'Range' ? 'Range' : l.cat === 'Food' ? 'Food' : l.cat === 'Beverage' ? 'Beverage' : 'Other');
const sumCat = (sale, c) => sale.lines.filter(l => catOf(l) === c).reduce((a, l) => a + l.price * l.qty, 0);
const sortDesc = (a, k) => a.slice().sort((x, y) => y[k] - x[k]);

// ---------- datasets ----------
export function visitsAll() {
  const s = S.get(), sales = new Map(s.sales.map(x => [x.id, x]));
  return s.tabs.filter(t => t.status === 'paid' && !t.walkin).map(t => { const sale = sales.get(t.saleId); if (!sale || sale.refunded) return null; return { tab: t, sale, playerId: t.playerId, player: t.player, bay: t.bayId, total: sale.total, buckets: sumCat(sale, 'Range'), food: sumCat(sale, 'Food'), bev: sumCat(sale, 'Beverage'), at: sale.time, date: dayKey(sale.time), cashier: sale.cashierName }; }).filter(Boolean);
}
const visitsIn = r => visitsAll().filter(v => inR(r, v.at));
export function groupPlayers(visits) {
  const m = new Map(); visits.forEach(v => { const g = m.get(v.playerId) || { player: v.player, visits: 0, total: 0, last: 0, first: Infinity }; g.visits++; g.total += v.total; g.last = Math.max(g.last, v.at); g.first = Math.min(g.first, v.at); m.set(v.playerId, g); });
  return [...m.entries()].map(([id, g]) => ({ id, ...g, avg: g.total / g.visits }));
}

export function metrics(r) {
  const s = S.get(), sales = s.sales.filter(x => inR(r, x.time)), paid = sales.filter(x => !x.refunded), visits = visitsIn(r);
  const cat = { Range: 0, Food: 0, Beverage: 0, Other: 0 }; paid.forEach(x => x.lines.forEach(l => { cat[catOf(l)] += l.price * l.qty; }));
  const collected = paid.filter(x => x.tender !== 'member').reduce((a, x) => a + x.total, 0), member = paid.filter(x => x.tender === 'member').reduce((a, x) => a + x.total, 0);
  const refunds = s.sales.filter(x => x.refunded && inR(r, x.refunded.at)), voidItems = s.tabs.flatMap(t => (t.voids || []).filter(v => inR(r, v.at)));
  const buckets = {}; s.tabs.forEach(t => t.items.forEach(i => { if (i.cat === 'Range' && inR(r, i.addedAt || t.created)) buckets[i.name] = (buckets[i.name] || 0) + i.qty; }));
  voidItems.forEach(v => { if (v.name in buckets) buckets[v.name] += v.qty; });
  const compCount = paid.reduce((a, x) => a + x.lines.filter(l => l.comp).reduce((q, l) => q + l.qty, 0), 0);
  const co = s.closeouts.filter(c => inR(r, c.time) && (c.status === 'ok' || c.status === 'approved'));
  const open = s.tabs.filter(t => t.status === 'open');
  const low = s.inventory.filter(i => stockLevel(i) !== 'ok');
  return {
    sales, paid, visits, cat, collected, member, total: paid.reduce((a, x) => a + x.total, 0),
    avgSpend: visits.length ? visits.reduce((a, v) => a + v.total, 0) / visits.length : 0,
    discounts: paid.reduce((a, x) => a + (x.discount?.amount || 0), 0), discCount: paid.filter(x => x.discount?.amount).length,
    comps: paid.reduce((a, x) => a + x.compValue, 0), compCount,
    overShort: co.reduce((a, c) => a + c.variance, 0), pendingCo: s.closeouts.filter(c => c.status === 'pending_approval').length,
    refundTotal: refunds.reduce((a, x) => a + x.total, 0), refundCount: refunds.length, voidTotal: voidItems.reduce((a, v) => a + v.value, 0), voidCount: voidItems.length,
    buckets, bucketTotal: Object.values(buckets).reduce((a, b) => a + b, 0),
    openTabs: open, openValue: open.reduce((a, t) => a + tabTotal(t), 0), overdue: open.filter(isOverdue).length, activeSessions: s.sessions.filter(x => !x.end).length,
    invValue: s.inventory.reduce((a, i) => a + i.qty * i.cost, 0), low,
  };
}
function trendItems(r, bucket) {
  const sales = S.get().sales.filter(x => !x.refunded && inR(r, x.time)), key = x => (bucket === 'hour' ? hourOf(x.time) : bucket === 'week' ? weekStart(dayKey(x.time)) : bucket === 'month' ? dayKey(x.time).slice(0, 7) : dayKey(x.time));
  const keys = []; if (bucket === 'hour') for (let h = OPEN_H; h <= CLOSE_H; h++) keys.push(h); else if (bucket === 'day') for (let k = r.fromKey; k <= r.toKey; k = addDays(k, 1)) keys.push(k); else for (let k = r.fromKey; k <= r.toKey; k = addDays(k, 1)) { const kk = bucket === 'week' ? weekStart(k) : k.slice(0, 7); if (!keys.includes(kk)) keys.push(kk); }
  const lbl = k => (bucket === 'hour' ? hourLbl(k) : bucket === 'day' ? shortKey(k) : bucket === 'week' ? 'Wk ' + shortKey(k) : new Date(k + '-15T12:00:00+08:00').toLocaleDateString('en-US', { month: 'short', year: '2-digit', timeZone: 'Asia/Manila' }));
  return keys.map(k => { const xs = sales.filter(x => key(x) === k); return { key: k, label: lbl(k), value: xs.reduce((a, x) => a + x.total, 0), count: xs.length, range: xs.reduce((a, x) => a + sumCat(x, 'Range'), 0), food: xs.reduce((a, x) => a + sumCat(x, 'Food'), 0), bev: xs.reduce((a, x) => a + sumCat(x, 'Beverage'), 0), other: xs.reduce((a, x) => a + sumCat(x, 'Other'), 0) }; });
}
const autoBucket = r => (r.days <= 1 ? 'hour' : r.days <= 62 ? 'day' : r.days <= 200 ? 'week' : 'month');

// ---------- management dashboard ----------
const filterBar = (st, act) => `<div class="filterbar"><div class="tabs-seg">${PRESETS.map(([k, l]) => `<button class="${st.preset === k ? 'on' : ''}" data-a="${act}" data-p="${k}">${l}</button>`).join('')}</div>${st.preset === 'custom' ? `<div class="row" style="gap:8px"><input type="date" value="${st.from || ''}" data-change="${act}Date" data-k="from" aria-label="From date" style="width:auto"><span class="muted">to</span><input type="date" value="${st.to || ''}" data-change="${act}Date" data-k="to" aria-label="To date" style="width:auto"></div>` : ''}</div>`;
defineView({ route: 'mgmt', label: 'Management Dashboard', icon: 'reports', group: 'Management', perm: 'dash.mgmt',
  render() {
    const r = rangeFor(ui.mgmt), m = metrics(r), at = attendanceToday(), cs = m.overShort;
    const players = sortDesc(groupPlayers(m.visits), 'total').slice(0, 5);
    const tr = trendItems(r, autoBucket(r));
    const hrsD = trendItems(r, 'hour');
    return head('Management Dashboard', `Owner overview · <b>${esc(r.label)}</b> · Philippine Time`, `<button class="btn secondary" data-a="nav" data-r="reports">${icon('reports')} All reports</button><button class="btn secondary" data-a="nav" data-r="approvals">${icon('check')} Approvals${S.get().approvals.some(a => a.status === 'pending') ? ` <span class="badge">${S.get().approvals.filter(a => a.status === 'pending').length}</span>` : ''}</button>`, true) + filterBar(ui.mgmt, 'mgPreset') + `
    <div class="grid g4 kpis">
      ${kpi(money(m.collected), 'Total sales collected', 'cash', 'green', m.member ? `+ ${money(m.member)} charged to members` : 'cash, GCash and card')}
      ${kpi(money(m.cat.Range), 'Range bucket sales', 'bucket')}
      ${kpi(money(m.cat.Food), 'Food sales', 'food')}
      ${kpi(money(m.cat.Beverage), 'Beverage sales', 'beverage')}
      ${kpi(money(m.avgSpend), 'Average spend per player', 'member', '', 'per paid visit')}
      ${kpi(String(m.visits.length), 'Number of paid visits', 'check', 'green', `${new Set(m.visits.map(v => v.playerId)).size} different players`)}
      ${kpi(String(m.openTabs.length), 'Active player tabs', 'tabs', 'orange', `live · ${m.activeSessions} sessions on the range`)}
      ${kpi(money(m.openValue), 'Unpaid open tabs', 'alert', m.overdue ? 'red' : 'orange', `live · ${m.overdue} overdue`)}
      ${kpi(money(m.discounts), 'Total discounts', 'alert', '', `${m.discCount} discounted sales`)}
      ${kpi(money(m.comps), 'Complimentary items', 'coffee', '', `${m.compCount} item${m.compCount === 1 ? '' : 's'}`)}
      ${kpi(money(cs), 'Cash over / (short)', 'closeout', cs < 0 ? 'red' : cs > 0 ? 'orange' : 'green', m.pendingCo ? `${m.pendingCo} closeout(s) awaiting approval` : 'approved closeouts')}
      ${kpi(money(m.invValue), 'Inventory value', 'inventory', m.low.length ? 'orange' : 'green', `${m.low.length} low-stock item${m.low.length === 1 ? '' : 's'}`)}
    </div>
    <h2 class="sec">Where the money stands</h2>
    <div class="ledger">
      <div class="ldg"><span class="lt">Buckets issued</span><b>${m.bucketTotal}</b><span class="ls">${Object.entries(m.buckets).map(([k, v]) => `${v} × ${esc(k.replace(/ \(.*/, ''))}`).join(' · ') || 'none'}</span></div>
      <div class="ldg warn"><span class="lt">Open unpaid player tabs <em>as of now</em></span><b>${money(m.openValue)}</b><span class="ls">${m.openTabs.length} tabs · ${m.overdue} overdue</span></div>
      <div class="ldg ok"><span class="lt">Completed paid sales</span><b>${money(m.total)}</b><span class="ls">${m.paid.length} receipts (incl. ${money(m.member)} on member accounts)</span></div>
      <div class="ldg bad"><span class="lt">Voids &amp; refunds</span><b>${money(m.refundTotal + m.voidTotal)}</b><span class="ls">${m.refundCount} refunded sales · ${m.voidCount} voided items</span></div>
      <div class="ldg"><span class="lt">Discounts &amp; complimentary</span><b>${money(m.discounts + m.comps)}</b><span class="ls">${money(m.discounts)} discounts · ${money(m.comps)} comps</span></div>
    </div>
    <div class="grid g2" style="margin-top:18px">
      <div class="card white"><h2>${r.days <= 1 ? 'Sales by hour' : 'Sales trend'}</h2>${columns(tr, { title: 'Sales trend' })}</div>
      <div class="card white"><h2>Sales mix</h2>${stack([{ label: 'Range buckets', value: m.cat.Range, color: SERIES[0] }, { label: 'Food', value: m.cat.Food, color: SERIES[1] }, { label: 'Beverages', value: m.cat.Beverage, color: SERIES[2] }, ...(m.cat.Other ? [{ label: 'Pro shop', value: m.cat.Other, color: SERIES[3] }] : [])])}<h3 style="margin:22px 0 10px">Payment methods</h3>${hbars(['cash', 'gcash', 'card', 'member'].map((k, i) => ({ label: { cash: 'Cash', gcash: 'GCash', card: 'Card', member: 'Charge to member' }[k], value: m.paid.filter(x => x.tender === k).reduce((a, x) => a + x.total, 0), color: SERIES[i] })))}</div>
      <div class="card white"><h2>Top spenders</h2>${hbars(players.map(p => ({ label: p.player, value: p.total, tip: `${money(p.total)} · ${p.visits} visits` })))}</div>
      <div class="card white"><h2>Busiest hours <span class="muted" style="font-weight:500;font-size:13px">sales by hour</span></h2>${columns(hrsD, { title: 'Sales by hour', color: 'var(--seq)' })}</div>
    </div>
    <h2 class="sec">Staff attendance today</h2>
    <div class="grid g4 kpis">${kpi(String(at.present), 'Staff present today', 'check', 'green')}${kpi(String(at.late), 'Late today', 'clock', at.late ? 'orange' : '')}${kpi(String(at.absent), 'Absent today', 'alert', at.absent ? 'red' : 'green')}${kpi(String(at.clockedIn), 'Currently clocked in', 'member', 'green')}${kpi(String(at.onBreak), 'Currently on break', 'coffee', at.onBreak ? 'orange' : '')}${kpi(hrs(at.hours), 'Total hours worked today', 'clock')}${kpi(hrs(at.ot), 'Total overtime hours', 'clock', at.ot ? 'orange' : '')}${kpi(String(at.pending), 'Pending attendance corrections', 'check', at.pending ? 'orange' : 'green')}</div>
    <div class="card white" style="margin-top:18px"><h2>Live staff status</h2>${liveTable(at.rows)}</div>`;
  } });
defineActions({
  mgPreset: ['dash.mgmt', d => { ui.mgmt.preset = d.p; render(); }],
  mgPresetDate: ['dash.mgmt', (d, e, el) => { ui.mgmt[d.k] = el.value; render(); }],
});

// ---------- reports ----------
const VR = { cols: (...c) => c };
function playerRows(list) { return list.map((p, i) => ({ rank: i + 1, player: p.player, visits: p.visits, last: p.last, total: p.total, avg: p.avg })); }
const REPORTS = [
  { id: 'top-visitors', group: 'Visitors & Players', title: 'Top visitors', filters: ['range'], build: r => { const g = sortDesc(groupPlayers(visitsIn(r)), 'visits'); return { summary: [{ label: 'Players', value: g.length }, { label: 'Paid visits', value: g.reduce((a, x) => a + x.visits, 0) }], chart: hbars(g.slice(0, 10).map(p => ({ label: p.player, value: p.visits, tip: `${p.visits} visits` })), { fmt: 'num' }), cols: [{ key: 'rank', label: '#', type: 'int' }, { key: 'player', label: 'Player' }, { key: 'visits', label: 'Total visits', type: 'int' }, { key: 'last', label: 'Last visit', type: 'dt' }, { key: 'total', label: 'Total spending', type: 'money' }, { key: 'avg', label: 'Average spend', type: 'money' }], rows: playerRows(g) }; } },
  { id: 'top-spenders', group: 'Visitors & Players', title: 'Top spenders', filters: ['range'], build: r => { const g = sortDesc(groupPlayers(visitsIn(r)), 'total'); return { summary: [{ label: 'Total spent', value: money(g.reduce((a, x) => a + x.total, 0)) }], chart: hbars(g.slice(0, 10).map(p => ({ label: p.player, value: p.total }))), cols: [{ key: 'rank', label: '#', type: 'int' }, { key: 'player', label: 'Player' }, { key: 'total', label: 'Total spent', type: 'money' }, { key: 'visits', label: 'Visits', type: 'int' }, { key: 'avg', label: 'Average spend', type: 'money' }, { key: 'last', label: 'Last visit', type: 'dt' }], rows: playerRows(g) }; } },
  { id: 'top-visit', group: 'Visitors & Players', title: 'Top spending per visit', filters: ['range'], build: r => { const v = sortDesc(visitsIn(r), 'total').slice(0, 30); return { summary: [{ label: 'Highest single tab', value: money(v[0]?.total || 0) }], chart: hbars(v.slice(0, 10).map(x => ({ label: `${x.player} · ${shortKey(x.date)}`, value: x.total }))), cols: [{ key: 'rank', label: '#', type: 'int' }, { key: 'player', label: 'Player' }, { key: 'bay', label: 'Bay' }, { key: 'total', label: 'Total bill', type: 'money' }, { key: 'buckets', label: 'Buckets', type: 'money' }, { key: 'food', label: 'Food', type: 'money' }, { key: 'bev', label: 'Beverages', type: 'money' }, { key: 'at', label: 'Date & time', type: 'dt' }, { key: 'cashier', label: 'Cashier' }], rows: v.map((x, i) => ({ rank: i + 1, player: x.player, bay: x.bay ? 'Bay ' + x.bay : '—', total: x.total, buckets: x.buckets, food: x.food, bev: x.bev, at: x.at, cashier: x.cashier })) }; } },
  { id: 'new-returning', group: 'Visitors & Players', title: 'New vs returning visitors', filters: ['range'], build: r => { const all = visitsAll(), inr = all.filter(v => inR(r, v.at)), ids = [...new Set(inr.map(v => v.playerId))]; const rows = ids.map(id => { const mine = all.filter(v => v.playerId === id), before = mine.filter(v => v.at < r.fromTs).length, now_ = mine.filter(v => inR(r, v.at)); return { player: now_[0].player, type: before ? 'Returning' : 'New', visits: now_.length, first: Math.min(...mine.map(v => v.at)), spent: now_.reduce((a, v) => a + v.total, 0) }; }).sort((a, b) => b.visits - a.visits); const nw = rows.filter(x => x.type === 'New').length, rt = rows.length - nw; return { summary: [{ label: 'New players', value: nw }, { label: 'Returning players', value: rt }, { label: 'Return rate', value: rows.length ? (rt / rows.length * 100).toFixed(0) + '%' : '—' }], chart: stack([{ label: 'New players', value: nw, color: SERIES[1] }, { label: 'Returning players', value: rt, color: SERIES[0] }], { fmt: 'num' }), cols: [{ key: 'player', label: 'Player' }, { key: 'type', label: 'Type' }, { key: 'visits', label: 'Visits in period', type: 'int' }, { key: 'first', label: 'First ever visit', type: 'dt' }, { key: 'spent', label: 'Spent in period', type: 'money' }], rows }; } },
  { id: 'inactive', group: 'Visitors & Players', title: 'Inactive regular visitors', filters: ['days'], build: (r, o) => { const all = visitsAll(), cut = now() - o.days * DAY, g = groupPlayers(all).filter(p => p.visits >= 3 && p.last < cut).sort((a, b) => b.visits - a.visits); return { summary: [{ label: `Regulars (3+ visits) not seen in ${o.days} days`, value: g.length }], note: 'A regular is a player with 3 or more completed paid visits.', cols: [{ key: 'player', label: 'Player' }, { key: 'visits', label: 'Past visits', type: 'int' }, { key: 'last', label: 'Last visit', type: 'dt' }, { key: 'since', label: 'Days away', type: 'int' }, { key: 'total', label: 'Lifetime spend', type: 'money' }, { key: 'avg', label: 'Average spend', type: 'money' }], rows: g.map(p => ({ player: p.player, visits: p.visits, last: p.last, since: Math.floor((now() - p.last) / DAY), total: p.total, avg: p.avg })) }; } },

  { id: 'trend', group: 'Sales & Operations', title: 'Daily / weekly / monthly sales trend', filters: ['range', 'bucket'], build: (r, o) => { const it = trendItems(r, o.bucket); return { summary: [{ label: 'Total sales', value: money(it.reduce((a, x) => a + x.value, 0)) }, { label: 'Receipts', value: it.reduce((a, x) => a + x.count, 0) }], chart: columns(it, { title: 'Sales trend' }), cols: [{ key: 'label', label: 'Period', sortKey: 'key' }, { key: 'count', label: 'Receipts', type: 'int' }, { key: 'range', label: 'Range buckets', type: 'money' }, { key: 'food', label: 'Food', type: 'money' }, { key: 'bev', label: 'Beverages', type: 'money' }, { key: 'value', label: 'Total (incl. tax)', type: 'money' }], rows: it }; } },
  { id: 'category', group: 'Sales & Operations', title: 'Sales by category', filters: ['range'], build: r => { const m = metrics(r), rows = [['Range Buckets', 'Range'], ['Food', 'Food'], ['Beverages', 'Beverage'], ['Pro Shop / other', 'Other']].map(([n, k]) => ({ category: n, qty: m.paid.reduce((a, x) => a + x.lines.filter(l => catOf(l) === k).reduce((q, l) => q + l.qty, 0), 0), amount: m.cat[k], share: 0 })), tot = rows.reduce((a, x) => a + x.amount, 0); rows.forEach(x => { x.share = tot ? x.amount / tot * 100 : 0; }); return { summary: [{ label: 'Gross category sales', value: money(tot) }], note: 'Before discounts and tax.', chart: stack(rows.map((x, i) => ({ label: x.category, value: x.amount, color: SERIES[i] }))), cols: [{ key: 'category', label: 'Category' }, { key: 'qty', label: 'Units sold', type: 'int' }, { key: 'amount', label: 'Sales', type: 'money' }, { key: 'share', label: 'Share', type: 'pct' }], rows }; } },
  { id: 'payment', group: 'Sales & Operations', title: 'Sales by payment method', filters: ['range'], build: r => { const m = metrics(r), L = { cash: 'Cash', gcash: 'GCash', card: 'Card', member: 'Charge to Member' }, rows = Object.keys(L).map(k => { const xs = m.paid.filter(x => x.tender === k); return { method: L[k], count: xs.length, amount: xs.reduce((a, x) => a + x.total, 0), share: 0 }; }), tot = rows.reduce((a, x) => a + x.amount, 0); rows.forEach(x => { x.share = tot ? x.amount / tot * 100 : 0; }); return { summary: [{ label: 'Total', value: money(tot) }], chart: hbars(rows.map((x, i) => ({ label: x.method, value: x.amount, color: SERIES[i] }))), cols: [{ key: 'method', label: 'Payment method' }, { key: 'count', label: 'Receipts', type: 'int' }, { key: 'amount', label: 'Amount', type: 'money' }, { key: 'share', label: 'Share', type: 'pct' }], rows }; } },
  { id: 'top-products', group: 'Sales & Operations', title: 'Top-selling products', filters: ['range'], build: r => { const rows = productRows(r).sort((a, b) => b.qty - a.qty); return { summary: [{ label: 'Units sold', value: rows.reduce((a, x) => a + x.qty, 0) }], chart: hbars(rows.slice(0, 10).map(x => ({ label: x.product, value: x.qty })), { fmt: 'num' }), cols: prodCols, rows: rows.map((x, i) => ({ rank: i + 1, ...x })) }; } },
  { id: 'least-products', group: 'Sales & Operations', title: 'Least-selling products', filters: ['range'], build: r => { const rows = productRows(r).sort((a, b) => a.qty - b.qty); return { summary: [{ label: 'Products with no sales', value: rows.filter(x => !x.qty).length }], chart: hbars(rows.slice(0, 10).map(x => ({ label: x.product, value: x.qty, color: 'var(--c3)' })), { fmt: 'num' }), cols: prodCols, rows: rows.map((x, i) => ({ rank: i + 1, ...x })) }; } },
  { id: 'buckets', group: 'Sales & Operations', title: 'Bucket issuance by size', filters: ['range'], build: r => { const m = metrics(r), rows = S.get().products.filter(p => p.cat === 'Range').map(p => ({ size: p.name, issued: m.buckets[p.name] || 0, amount: (m.buckets[p.name] || 0) * p.price, share: 0 })), tot = rows.reduce((a, x) => a + x.issued, 0); rows.forEach(x => { x.share = tot ? x.issued / tot * 100 : 0; }); return { summary: [{ label: 'Buckets issued', value: tot }], chart: hbars(rows.map((x, i) => ({ label: x.size, value: x.issued, color: SERIES[i] })), { fmt: 'num' }), cols: [{ key: 'size', label: 'Bucket size' }, { key: 'issued', label: 'Issued', type: 'int' }, { key: 'amount', label: 'Value at list price', type: 'money' }, { key: 'share', label: 'Share', type: 'pct' }], rows }; } },
  { id: 'avg-tab', group: 'Sales & Operations', title: 'Average player tab value', filters: ['range'], build: r => { const v = visitsIn(r), tot = v.map(x => x.total).sort((a, b) => a - b), byDay = new Map(); v.forEach(x => (byDay.get(x.date) || byDay.set(x.date, []).get(x.date)).push(x.total)); const rows = [...byDay.entries()].sort().map(([d, a]) => ({ date: d, visits: a.length, avg: a.reduce((p, q) => p + q, 0) / a.length, total: a.reduce((p, q) => p + q, 0) })); return { summary: [{ label: 'Average tab', value: money(tot.length ? tot.reduce((a, b) => a + b, 0) / tot.length : 0) }, { label: 'Median', value: money(tot[Math.floor(tot.length / 2)] || 0) }, { label: 'Highest', value: money(tot[tot.length - 1] || 0) }, { label: 'Lowest', value: money(tot[0] || 0) }, { label: 'Paid visits', value: tot.length }], chart: columns(rows.map(x => ({ label: shortKey(x.date), value: x.avg })), { title: 'Average tab by day' }), cols: [{ key: 'date', label: 'Date', type: 'date' }, { key: 'visits', label: 'Paid visits', type: 'int' }, { key: 'avg', label: 'Average tab', type: 'money' }, { key: 'total', label: 'Total', type: 'money' }], rows: rows.reverse() }; } },
  { id: 'avg-session', group: 'Sales & Operations', title: 'Average session duration', filters: ['range'], build: r => { const ss = S.get().sessions.filter(x => x.end && inR(r, x.start)), dur = x => (x.end - x.start) / 60e3, by = new Map(); ss.forEach(x => (by.get(x.bucket) || by.set(x.bucket, []).get(x.bucket)).push(dur(x))); const avg = a => (a.length ? a.reduce((p, q) => p + q, 0) / a.length : 0); const rows = [...by.entries()].map(([b, a]) => ({ bucket: b, sessions: a.length, avg: avg(a), longest: Math.max(...a), shortest: Math.min(...a) })); return { summary: [{ label: 'Average session', value: durFmt(avg(ss.map(dur))) }, { label: 'Sessions', value: ss.length }, { label: 'Longest', value: durFmt(Math.max(0, ...ss.map(dur))) }], note: 'Session length runs from bay assignment until payment is collected.', chart: hbars(rows.map(x => ({ label: x.bucket, value: x.avg, tip: durFmt(x.avg) })), { valFmt: v => durFmt(v) }), cols: [{ key: 'bucket', label: 'Bucket size' }, { key: 'sessions', label: 'Sessions', type: 'int' }, { key: 'avg', label: 'Average duration', type: 'dur' }, { key: 'longest', label: 'Longest', type: 'dur' }, { key: 'shortest', label: 'Shortest', type: 'dur' }], rows }; } },
  { id: 'bay-util', group: 'Sales & Operations', title: 'Bay utilization (Bay 1 – Bay 15)', filters: ['range'], build: r => { const s = S.get(), t = now(); let avail = 0; const windows = []; for (let k = r.fromKey; k <= r.toKey; k = addDays(k, 1)) { const a = manilaTs(k, '0' + OPEN_H + ':00'), b = Math.min(manilaTs(k, CLOSE_H + ':00'), t); if (b > a) { windows.push([a, b]); avail += (b - a) / 60e3; } } const rows = s.bays.map(b => { const ss = s.sessions.filter(x => x.bayId === b.id && (x.end || t) > r.fromTs && x.start < r.toTs); let busy = 0; ss.forEach(x => windows.forEach(([a, z]) => { busy += Math.max(0, Math.min(x.end || t, z) - Math.max(x.start, a)) / 60e3; })); return { bay: 'Bay ' + b.id, n: b.id, sessions: ss.length, busy, avail, util: avail ? busy / avail * 100 : 0 }; }); const tot = rows.reduce((a, x) => a + x.busy, 0); return { summary: [{ label: 'Average utilization', value: (avail ? tot / (avail * 15) * 100 : 0).toFixed(1) + '%' }, { label: 'Sessions', value: rows.reduce((a, x) => a + x.sessions, 0) }], note: `Utilization = bay-in-use time ÷ operating hours (${OPEN_H}:00 AM – ${CLOSE_H - 12}:00 PM).`, chart: hbars(rows.map(x => ({ label: x.bay, value: x.util, color: 'var(--seq)' })), { valFmt: v => v.toFixed(0) + '%', max: Math.max(100, ...rows.map(x => x.util)) }), cols: [{ key: 'bay', label: 'Bay', sortKey: 'n' }, { key: 'sessions', label: 'Sessions', type: 'int' }, { key: 'busy', label: 'Time in use', type: 'dur' }, { key: 'avail', label: 'Operating time', type: 'dur' }, { key: 'util', label: 'Utilization', type: 'pct' }], rows }; } },
  { id: 'peak', group: 'Sales & Operations', title: 'Peak operating hours', filters: ['range'], build: r => { const s = S.get(), rows = []; for (let h = OPEN_H; h <= CLOSE_H; h++) { const ss = s.sessions.filter(x => inR(r, x.start) && hourOf(x.start) === h), sl = s.sales.filter(x => !x.refunded && inR(r, x.time) && hourOf(x.time) === h); rows.push({ hour: `${h % 12 || 12}:00 ${h < 12 ? 'AM' : 'PM'}`, h, sessions: ss.length, receipts: sl.length, sales: sl.reduce((a, x) => a + x.total, 0) }); } const top = [...rows].sort((a, b) => b.sessions - a.sessions)[0]; return { summary: [{ label: 'Busiest hour (sessions)', value: top?.sessions ? top.hour : '—' }], chart: columns(rows.map(x => ({ label: hourLbl(x.h), value: x.sessions, tip: `${x.sessions} sessions · ${money(x.sales)}` })), { fmt: 'num', title: 'Sessions started by hour', color: 'var(--seq)' }), cols: [{ key: 'hour', label: 'Hour', sortKey: 'h' }, { key: 'sessions', label: 'Sessions started', type: 'int' }, { key: 'receipts', label: 'Receipts', type: 'int' }, { key: 'sales', label: 'Sales', type: 'money' }], rows }; } },
  { id: 'open-tabs', group: 'Sales & Operations', title: 'Open tabs and unpaid balances', filters: [], build: () => { const s = S.get(), list = s.tabs.filter(t => t.status === 'open' || t.status === 'closed_unpaid'); const rows = list.map(t => ({ player: t.player, id: t.id, opened: t.created, age: Math.floor((now() - t.created) / 3600e3), bay: t.bayId && t.status === 'open' ? 'Bay ' + t.bayId : '—', items: t.items.reduce((a, i) => a + i.qty, 0), balance: t.status === 'open' ? tabTotal(t) : t.unpaid, status: t.status === 'closed_unpaid' ? 'Closed unpaid (written off)' : isOverdue(t) ? 'Overdue' : 'Open' })).sort((a, b) => b.balance - a.balance); return { summary: [{ label: 'Open tabs', value: rows.filter(x => x.status !== 'Closed unpaid (written off)').length }, { label: 'Unpaid balance', value: money(rows.filter(x => x.status !== 'Closed unpaid (written off)').reduce((a, x) => a + x.balance, 0)) }, { label: 'Overdue', value: rows.filter(x => x.status === 'Overdue').length }, { label: 'Written off', value: money(rows.filter(x => x.status.startsWith('Closed')).reduce((a, x) => a + x.balance, 0)) }], cols: [{ key: 'player', label: 'Player' }, { key: 'id', label: 'Tab' }, { key: 'opened', label: 'Opened', type: 'dt' }, { key: 'age', label: 'Age (hours)', type: 'int' }, { key: 'bay', label: 'Bay' }, { key: 'items', label: 'Items', type: 'int' }, { key: 'balance', label: 'Balance', type: 'money' }, { key: 'status', label: 'Status' }], rows }; } },
  { id: 'adjustments', group: 'Sales & Operations', title: 'Discounts, voids, refunds and complimentary items', filters: ['range'], build: r => { const T = { discount: 'Discount', void_item: 'Void item', refund: 'Refund / void', comp: 'Complimentary', price_override: 'Price override', tab_close_unpaid: 'Closed unpaid' }, list = S.get().approvals.filter(a => a.status === 'approved' && T[a.type] && inR(r, a.decidedAt)).sort((a, b) => b.decidedAt - a.decidedAt), by = k => list.filter(a => a.type === k).reduce((x, a) => x + a.amount, 0); return { summary: [{ label: 'Discounts', value: money(by('discount')) }, { label: 'Voided items', value: money(by('void_item')) }, { label: 'Refunds / voids', value: money(by('refund')) }, { label: 'Complimentary', value: money(by('comp')) }, { label: 'Price overrides', value: money(by('price_override')) }], cols: [{ key: 'at', label: 'Decided', type: 'dt' }, { key: 'type', label: 'Type' }, { key: 'ref', label: 'Tab / receipt' }, { key: 'amount', label: 'Amount', type: 'money' }, { key: 'by', label: 'Requested by' }, { key: 'approver', label: 'Approved by' }, { key: 'reason', label: 'Reason' }], rows: list.map(a => ({ at: a.decidedAt, type: T[a.type], ref: a.refLabel, amount: a.amount, by: a.requestedByName, approver: a.decidedByName + (a.direct ? ' (direct)' : ''), reason: a.reason })) }; } },
  { id: 'cashier-perf', group: 'Sales & Operations', title: 'Cashier performance', filters: ['range'], build: r => { const s = S.get(), ids = [...new Set([...s.users.filter(u => u.role === 'cashier').map(u => u.id), ...s.sales.filter(x => inR(r, x.time)).map(x => x.cashier)])].filter(id => id !== 'system'); const rows = ids.map(id => { const sl = s.sales.filter(x => x.cashier === id && inR(r, x.time)), ap = s.approvals.filter(a => a.requestedBy === id && inR(r, a.requestedAt)); return { cashier: S.userName(id), tx: sl.length, sales: sl.filter(x => !x.refunded).reduce((a, x) => a + x.total, 0), discReq: ap.filter(a => a.type === 'discount').length, voidReq: ap.filter(a => a.type === 'void_item' || a.type === 'refund').length, over: s.closeouts.filter(c => c.cashier === id && inR(r, c.time) && (c.status === 'ok' || c.status === 'approved')).reduce((a, c) => a + c.variance, 0) }; }).sort((a, b) => b.sales - a.sales); return { summary: [{ label: 'Transactions', value: rows.reduce((a, x) => a + x.tx, 0) }, { label: 'Sales collected', value: money(rows.reduce((a, x) => a + x.sales, 0)) }], chart: hbars(rows.map(x => ({ label: x.cashier, value: x.sales }))), cols: [{ key: 'cashier', label: 'Cashier' }, { key: 'tx', label: 'Transactions processed', type: 'int' }, { key: 'sales', label: 'Sales collected', type: 'money' }, { key: 'discReq', label: 'Discounts requested', type: 'int' }, { key: 'voidReq', label: 'Voids requested', type: 'int' }, { key: 'over', label: 'Cash over / (short)', type: 'money' }], rows }; } },
  { id: 'closeout', group: 'Sales & Operations', title: 'Daily cashier closeout report', filters: ['range'], build: r => { const s = S.get(), list = s.closeouts.filter(c => inR(r, c.time)).sort((a, b) => b.time - a.time); return { summary: [{ label: 'Closeouts', value: list.length }, { label: 'Net over / (short)', value: money(list.filter(c => c.status === 'ok' || c.status === 'approved').reduce((a, c) => a + c.variance, 0)) }, { label: 'Awaiting approval', value: list.filter(c => c.status === 'pending_approval').length }], cols: [{ key: 'date', label: 'Date', type: 'date' }, { key: 'cashier', label: 'Cashier' }, { key: 'expected', label: 'Expected cash', type: 'money' }, { key: 'counted', label: 'Counted', type: 'money' }, { key: 'variance', label: 'Over / (short)', type: 'money' }, { key: 'cash', label: 'Cash sales', type: 'money' }, { key: 'gcash', label: 'GCash', type: 'money' }, { key: 'card', label: 'Card', type: 'money' }, { key: 'member', label: 'Member charges', type: 'money' }, { key: 'status', label: 'Status' }, { key: 'approver', label: 'Approved by' }], rows: list.map(c => { const ap = s.approvals.find(a => a.id === c.approvalId); return { date: c.date, cashier: c.cashierName, expected: c.expectedCash, counted: c.counted, variance: c.variance, cash: c.cash, gcash: c.gcash || 0, card: c.card, member: c.member || 0, status: ({ ok: 'Balanced', approved: 'Variance approved', pending_approval: 'Awaiting approval', rejected: 'Rejected' })[c.status], approver: ap?.decidedByName || '' }; }) }; } },
  { id: 'inv-move', group: 'Sales & Operations', title: 'Food & beverage inventory movement', filters: ['range'], build: r => { const s = S.get(), rows = s.inventory.map(i => { const mv = s.moves.filter(m => m.invId === i.id), after = mv.filter(m => m.ts >= r.toTs).reduce((a, m) => a + m.delta, 0), inr = mv.filter(m => inR(r, m.ts)), sum = f => inr.filter(f).reduce((a, m) => a + m.delta, 0), closing = i.qty - after, net = inr.reduce((a, m) => a + m.delta, 0); return { item: i.name, unit: i.unit, opening: closing - net, received: sum(m => m.type === 'receive'), sold: -sum(m => m.type === 'sale'), returned: sum(m => m.type === 'void'), adjusted: sum(m => m.type === 'adjust'), closing, cost: -sum(m => m.type === 'sale') * i.cost }; }); return { summary: [{ label: 'Cost of goods sold', value: money(rows.reduce((a, x) => a + x.cost, 0)) }], note: 'Opening and closing are derived from the stock movement ledger.', cols: [{ key: 'item', label: 'Item' }, { key: 'unit', label: 'Unit' }, { key: 'opening', label: 'Opening', type: 'num' }, { key: 'received', label: 'Received', type: 'num' }, { key: 'sold', label: 'Sold / used', type: 'num' }, { key: 'returned', label: 'Voided (returned)', type: 'num' }, { key: 'adjusted', label: 'Adjusted', type: 'num' }, { key: 'closing', label: 'Closing', type: 'num' }, { key: 'cost', label: 'Cost of sold', type: 'money' }], rows }; } },
  { id: 'low-stock', group: 'Sales & Operations', title: 'Low-stock and out-of-stock', filters: [], build: () => { const rows = S.get().inventory.filter(i => stockLevel(i) !== 'ok').map(i => ({ item: i.name, qty: i.qty, par: i.par, crit: i.critical, status: { out: 'Out of stock', critical: 'Critical', low: 'Low' }[stockLevel(i)], short: Math.max(0, i.par - i.qty), cost: Math.max(0, i.par - i.qty) * i.cost })).sort((a, b) => b.cost - a.cost); return { summary: [{ label: 'Items needing reorder', value: rows.length }, { label: 'Est. cost to reach par', value: money(rows.reduce((a, x) => a + x.cost, 0)) }], cols: [{ key: 'item', label: 'Item' }, { key: 'qty', label: 'On hand', type: 'num' }, { key: 'par', label: 'Par', type: 'num' }, { key: 'crit', label: 'Critical at', type: 'num' }, { key: 'status', label: 'Status' }, { key: 'short', label: 'Short of par', type: 'num' }, { key: 'cost', label: 'Est. reorder cost', type: 'money' }], rows }; } },
  ...ATT_REPORTS,
];
const prodCols = [{ key: 'rank', label: '#', type: 'int' }, { key: 'product', label: 'Product' }, { key: 'cat', label: 'Category' }, { key: 'qty', label: 'Units sold', type: 'int' }, { key: 'amount', label: 'Sales', type: 'money' }, { key: 'share', label: 'Share of units', type: 'pct' }];
function productRows(r) { const m = metrics(r), by = {}; m.paid.forEach(x => x.lines.forEach(l => { const g = by[l.name] || (by[l.name] = { qty: 0, amount: 0 }); g.qty += l.qty; g.amount += l.price * l.qty; })); const tot = Object.values(by).reduce((a, b) => a + b.qty, 0); return S.get().products.map(p => ({ product: p.name, cat: p.cat, qty: by[p.name]?.qty || 0, amount: by[p.name]?.amount || 0, share: tot ? (by[p.name]?.qty || 0) / tot * 100 : 0 })); }

function runReport(id) {
  const def = REPORTS.find(x => x.id === id) || REPORTS[0], f = ui.rep, r = rangeFor(f), res = def.build(r, f);
  return { def, r, res };
}
const filterLine = (def, f, r) => [def.filters.includes('range') || def.filters.includes('staff') ? `Period: ${r.label}` : 'As of now', f.staff !== 'all' && def.filters.some(x => x.startsWith('staff')) ? 'Staff: ' + S.userName(f.staff) : '', f.role !== 'all' && def.filters.includes('role') ? 'Role: ' + ROLE_LABEL[f.role] : ''].filter(Boolean).join(' · ');
function staticTable(cols, rows) { return `<table class="doc-table"><thead><tr>${cols.map(c => `<th class="${['money', 'int', 'num', 'pct', 'hrs', 'dur'].includes(c.type) ? 'right' : ''}">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(rw => `<tr>${cols.map(c => `<td class="${['money', 'int', 'num', 'pct', 'hrs', 'dur'].includes(c.type) ? 'right' : ''}">${fmtCell(c.type, rw[c.key])}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${cols.length}">No records.</td></tr>`}</tbody></table>`; }
const sumHtml = sm => sm?.length ? `<div class="sumrow">${sm.map(x => `<div class="sumchip"><span>${esc(x.label)}</span><b>${typeof x.value === 'number' ? num(x.value) : x.value}</b></div>`).join('')}</div>` : '';

defineView({ route: 'reports', label: 'Reports', icon: 'reports', group: 'Management', perm: 'reports.view',
  render() {
    const f = ui.rep, { def, r, res } = runReport(f.id), groups = [...new Set(REPORTS.map(x => x.group))], s = S.get();
    const staffOpts = `<option value="all">All staff</option>${s.users.map(u => `<option value="${u.id}" ${f.staff === u.id ? 'selected' : ''}>${esc(u.name)}</option>`).join('')}`;
    const has = k => def.filters.includes(k);
    const filters = `<div class="filterbar">${has('range') ? `<div class="tabs-seg">${[...PRESETS.slice(0, 4), ['last30', 'Last 30 days'], PRESETS[4]].map(([k, l]) => `<button class="${f.preset === k ? 'on' : ''}" data-a="repPreset" data-p="${k}">${l}</button>`).join('')}</div>${f.preset === 'custom' ? `<div class="row" style="gap:8px"><input type="date" value="${f.from || ''}" data-change="repDate" data-k="from" aria-label="From date" style="width:auto"><span class="muted">to</span><input type="date" value="${f.to || ''}" data-change="repDate" data-k="to" aria-label="To date" style="width:auto"></div>` : ''}` : ''}
      ${has('staff') || has('staffOnly') ? `<select data-change="repSel" data-k="staff" aria-label="Staff" style="width:auto">${staffOpts}</select>` : ''}
      ${has('role') ? `<select data-change="repSel" data-k="role" aria-label="Role" style="width:auto"><option value="all">All roles</option>${['cashier', 'attendant', 'server', 'admin'].map(k => `<option value="${k}" ${f.role === k ? 'selected' : ''}>${ROLE_LABEL[k]}</option>`).join('')}</select>` : ''}
      ${has('days') ? `<select data-change="repSel" data-k="days" aria-label="Inactive for" style="width:auto">${[7, 14, 21, 30, 60].map(d => `<option value="${d}" ${+f.days === d ? 'selected' : ''}>Not seen in ${d} days</option>`).join('')}</select>` : ''}
      ${has('bucket') ? `<div class="tabs-seg">${[['day', 'Daily'], ['week', 'Weekly'], ['month', 'Monthly']].map(([k, l]) => `<button class="${f.bucket === k ? 'on' : ''}" data-a="repBucket" data-b="${k}">${l}</button>`).join('')}</div>` : ''}</div>`;
    const exp = Auth.can('reports.export') ? `<div class="actions"><button class="btn secondary" data-a="repXlsx">${icon('inventory')} Excel</button><button class="btn secondary" data-a="repPdf">${icon('print')} PDF</button></div>` : '';
    return head('Reports', 'Visitors, sales, operations and attendance. Sortable tables with Excel and PDF export.') + `<div class="repwrap"><nav class="repnav" aria-label="Reports">${groups.map(g => `<div class="rg">${g}</div>${REPORTS.filter(x => x.group === g).map(x => `<button class="${x.id === def.id ? 'on' : ''}" data-a="repPick" data-id="${x.id}">${esc(x.title)}</button>`).join('')}`).join('')}</nav>
      <div class="repmain">${filters}<div class="card white"><div class="row" style="justify-content:space-between;align-items:flex-start"><div><h2 style="margin-bottom:2px">${esc(def.title)}</h2><div class="muted" style="font-size:13px">${esc(filterLine(def, f, r))}</div></div>${exp}</div>${sumHtml(res.summary)}${res.note ? `<div class="notice green" style="margin-top:12px">${esc(res.note)}</div>` : ''}${res.chart ? `<div class="chartbox">${res.chart}</div>` : ''}${table('rep-' + def.id + f.bucket, res.cols, res.rows, { limit: 400 })}</div></div></div>`;
  } });
defineActions({
  repPick: ['reports.view', d => { ui.rep.id = d.id; render(); }],
  repPreset: ['reports.view', d => { ui.rep.preset = d.p; render(); }],
  repDate: ['reports.view', (d, e, el) => { ui.rep[d.k] = el.value; render(); }],
  repSel: ['reports.view', (d, e, el) => { ui.rep[d.k] = el.value; render(); }],
  repBucket: ['reports.view', d => { ui.rep.bucket = d.b; render(); }],
  repXlsx: ['reports.export', () => {
    const { def, r, res } = runReport(ui.rep.id), meta = [CLUB, 'Range & Café Operations', filterLine(def, ui.rep, r), `Generated ${fmtDT(now())} PHT by ${Auth.user().name}`, ...(res.summary || []).map(x => `${x.label}: ${typeof x.value === 'number' ? x.value : String(x.value).replace(/[₱,]/g, '')}`)];
    download(xlsxBlob(def.title, meta, res.cols, res.rows), `Cattle-Creek_${def.id}_${r.fromKey}_${r.toKey}.xlsx`);
    S.commit(s => S.log(s, 'report_export', `Exported "${def.title}" to Excel (${r.label})`)); toast('Excel file downloaded');
  }],
  repPdf: ['reports.export', () => {
    const { def, r, res } = runReport(ui.rep.id);
    S.commit(s => S.log(s, 'report_export', `Opened "${def.title}" for PDF/print (${r.label})`));
    docModal(reportDoc(def.title, `${sumHtml(res.summary)}${res.note ? `<p class="muted">${esc(res.note)}</p>` : ''}${res.chart ? `<div class="chartbox">${res.chart}</div>` : ''}${staticTable(res.cols, res.rows.slice(0, 500))}`, filterLine(def, ui.rep, r)));
  }],
});
