// Generates supabase/migrations/0003_role_permissions.sql and supabase/seed.sql from the in-app demo dataset.
// Run:  npx vite-node scripts/export-seed-sql.ts
import { writeFileSync } from 'node:fs';
import { DEFAULT_ACCESS } from '../src/lib/rbac';
import { seedDB } from '../src/lib/seed';

const db = seedDB();
const q = (v: unknown): string => {
  if (v === undefined || v === null) return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const rename: Record<string, Record<string, string>> = { periods: { start: 'period_start', end: 'period_end' } };
const tables = ['branches', 'clients', 'sites', 'communications', 'complaints', 'services', 'inquiries', 'quotations', 'employees', 'jobs', 'attendance', 'corrections', 'holidays', 'reviews', 'adjustments', 'periods', 'runs', 'locations', 'items', 'stock', 'requests', 'assets', 'checkouts', 'tickets', 'invoices', 'payments', 'expenses', 'petty', 'workflows', 'variations', 'incidents', 'discount_requests', 'client_feedback', 'back_jobs', 'payment_confirmations', 'ocular_visits', 'quote_images'] as const;

// permissions (part of the schema — needed in production, not only for demo)
const perms = Object.entries(DEFAULT_ACCESS).flatMap(([role, list]) => list.map((p) => `('${role}', '${p}')`));
writeFileSync('supabase/migrations/0003_role_permissions.sql', `-- Default role → permission matrix (generated from src/lib/rbac.ts). The Owner can edit it in Admin → Permissions.\ninsert into public.role_permissions (role, permission) values\n${perms.join(',\n')}\non conflict do nothing;\n`);

const out: string[] = ['-- TopMop demo dataset (generated by scripts/export-seed-sql.ts). Dates are relative to the day it was generated.',
  '-- Run as the postgres role. Triggers are bypassed so historical approved records can be loaded as-is.', 'set session_replication_role = replica;', 'begin;'];
let total = 0;
for (const t of tables) {
  for (const row of (db as unknown as Record<string, Record<string, unknown>[]>)[t]) {
    const r = { ...row }; const map = rename[t] ?? {};
    const cols = Object.keys(r).filter((k) => r[k] !== undefined);
    out.push(`insert into public.${t} (${cols.map((c) => map[c] ?? c).join(', ')}) values (${cols.map((c) => q(r[c])).join(', ')});`);
    total++;
  }
}
out.push(`insert into public.settings (id, data) values ('main', ${q(db.settings)}) on conflict (id) do update set data = excluded.data;`, 'commit;', 'set session_replication_role = default;');
writeFileSync('supabase/seed.sql', out.join('\n') + '\n');
console.log(`Wrote ${total} rows to supabase/seed.sql`);
